(()=>{'use strict';
const c=document.querySelector('#game'),x=c.getContext('2d'),$=id=>document.getElementById(id);let W,H,D=1,last=0,state='menu',run=null,pending=null,parts=[],floats=[];
const ui={hp:$('hp'),power:$('power'),coins:$('coins'),progress:$('progress'),msg:$('msg'),start:$('start'),loot:$('loot'),result:$('result'),controls:$('controls')};
const p={lane:1,target:1,y:0,hp:100,maxHp:100,power:10,coins:0,attackCd:0,dodgeCd:0,inv:0,swing:0,weapon:1,armor:1};
const loot=[{type:'weapon',icon:'🗡️',name:'Hoja de cobre',power:3,color:'#d08c60'},{type:'armor',icon:'🥋',name:'Coraza de cuero',power:2,hp:15,color:'#a47148'},{type:'weapon',icon:'⚔️',name:'Espada del bosque',power:5,color:'#7bd389'},{type:'armor',icon:'🛡️',name:'Armadura de guardia',power:4,hp:25,color:'#90a4ae'},{type:'weapon',icon:'🔱',name:'Filo del guardián',power:8,color:'#ffd166'}];
function resize(){D=Math.min(devicePixelRatio||1,2);W=c.clientWidth;H=c.clientHeight;c.width=W*D;c.height=H*D;x.setTransform(D,0,0,D,0,0);p.y=H*.73}addEventListener('resize',resize);resize();
function say(t){ui.msg.textContent=t;clearTimeout(say.t);say.t=setTimeout(()=>{if(state==='playing')ui.msg.textContent=''},1200)}
function hud(){ui.hp.textContent=Math.max(0,Math.ceil(p.hp));ui.power.textContent=p.power;ui.coins.textContent=p.coins;ui.progress.style.width=(run?Math.min(100,run.distance/run.length*100):0)+'%'}
function newRun(){p.hp=p.maxHp;p.lane=p.target=1;p.attackCd=p.dodgeCd=p.inv=0;parts=[];floats=[];run={distance:0,length:1100,speed:62,spawned:0,boss:false,enemies:[],chests:[],kills:0,loot:0,over:false};state='playing';ui.start.classList.remove('show');ui.result.classList.remove('show');ui.loot.classList.remove('show');ui.controls.classList.add('show');say('¡Adelante!');hud()}
function laneX(l,z=0){return W/2+(l-1)*W*(.20+.11*z)}
function spawn(kind='goblin',lane=Math.floor(Math.random()*3),z=0){const d={slime:{hp:12,damage:7,speed:.19,size:24,color:'#62d273',reward:3},goblin:{hp:20,damage:10,speed:.23,size:28,color:'#8bc34a',reward:5},orc:{hp:34,damage:14,speed:.20,size:34,color:'#a56b46',reward:8},boss:{hp:145,damage:19,speed:.14,size:54,color:'#7f1d1d',reward:40}}[kind];run.enemies.push({kind,lane,z,hp:d.hp,maxHp:d.hp,...d,hit:0,dead:false})}
function chest(){run.chests.push({lane:Math.floor(Math.random()*3),z:0,opened:false})}
function move(d){if(state==='playing')p.target=Math.max(0,Math.min(2,p.target+d))}
function burst(px,py,col,n){for(let i=0;i<n;i++)parts.push({x:px,y:py,vx:(Math.random()-.5)*160,vy:(Math.random()-.8)*160,life:.55,col})}
function ft(t,px,py,col){floats.push({t,x:px,y:py,life:.8,col})}
function attack(){if(state!=='playing'||p.attackCd>0)return;p.attackCd=.42;p.swing=.22;for(const e of run.enemies){if(!e.dead&&e.lane===p.target&&e.z>.74&&e.z<1.08){const dmg=p.power+Math.floor(Math.random()*4);e.hp-=dmg;e.hit=.12;ft('-'+dmg,laneX(e.lane,e.z),p.y-90,'#fff');burst(laneX(e.lane,e.z),p.y-60,e.color,8);if(e.hp<=0){e.dead=true;run.kills++;p.coins+=e.reward;ft('+'+e.reward+' 🪙',laneX(e.lane,e.z),p.y-110,'#ffd166');if(e.kind==='boss')end(true)}hud();return}}burst(laneX(p.target,1),p.y-35,'#dbeafe',3)}
function dodge(){if(state==='playing'&&p.dodgeCd<=0){p.dodgeCd=1.1;p.inv=.55;say('¡Esquiva!')}}
function damage(n){if(p.inv>0)return;p.hp-=n;p.inv=.55;ft('-'+n,W/2,p.y-80,'#ff6b6b');burst(laneX(p.target,1),p.y-40,'#ef476f',10);navigator.vibrate?.(45);hud();if(p.hp<=0)end(false)}
function offer(){pending={...loot[Math.floor(Math.random()*(run.boss?loot.length:loot.length-1))]};$('lootIcon').textContent=pending.icon;$('lootName').textContent=pending.name;$('lootDesc').textContent=pending.type==='weapon'?`+${pending.power} de poder. El arma cambiará en el personaje.`:`+${pending.power} de poder y +${pending.hp} de vida máxima.`;ui.loot.classList.add('show');ui.controls.classList.remove('show');state='loot'}
function equip(){if(!pending)return;p.power+=pending.power;if(pending.type==='weapon')p.weapon++;else{p.armor++;p.maxHp+=pending.hp;p.hp=Math.min(p.maxHp,p.hp+pending.hp)}run.loot++;pending=null;ui.loot.classList.remove('show');ui.controls.classList.add('show');state='playing';say('Equipo mejorado');hud()}
function sell(){p.coins+=12;pending=null;ui.loot.classList.remove('show');ui.controls.classList.add('show');state='playing';say('+12 monedas');hud()}
function end(win){if(run?.over)return;run.over=true;state='result';ui.controls.classList.remove('show');setTimeout(()=>{$('resultLabel').textContent=win?'EXPEDICIÓN COMPLETADA':'DERROTA';$('resultTitle').textContent=win?'¡Guardián vencido!':'Has caído';$('resultStats').textContent=`${run.kills} enemigos · ${run.loot} mejoras · Poder ${p.power} · ${p.coins} monedas`;ui.result.classList.add('show')},350)}
function update(dt){if(state!=='playing'||!run)return;p.attackCd=Math.max(0,p.attackCd-dt);p.dodgeCd=Math.max(0,p.dodgeCd-dt);p.inv=Math.max(0,p.inv-dt);p.swing=Math.max(0,p.swing-dt);p.lane+=(p.target-p.lane)*Math.min(1,dt*12);run.distance+=run.speed*dt;const step=Math.floor(run.distance/92);if(step>run.spawned&&!run.boss){run.spawned=step;if(step===3||step===7)chest();else if(step<11){spawn(step>7?'orc':step>3?'goblin':'slime');if(step===6)spawn('slime',Math.floor(Math.random()*2)*2)}}if(run.distance/run.length>.86&&!run.boss){run.boss=true;run.speed=28;spawn('boss',1,-.1);say('GUARDIÁN DEL BOSQUE')}for(const e of run.enemies){if(e.dead){e.z+=dt*.9;continue}e.z+=dt*e.speed*(run.boss?1.35:1);e.hit=Math.max(0,e.hit-dt);if(e.z>1.04){damage(e.damage);e.dead=true}}for(const q of run.chests){if(!q.opened){q.z+=dt*.2;if(q.z>.92){q.opened=true;offer();break}}}run.enemies=run.enemies.filter(e=>e.z<1.35);run.chests=run.chests.filter(q=>q.z<1.25);for(const a of parts){a.x+=a.vx*dt;a.y+=a.vy*dt;a.vy+=260*dt;a.life-=dt}parts=parts.filter(a=>a.life>0);for(const f of floats){f.y-=35*dt;f.life-=dt}floats=floats.filter(f=>f.life>0);hud()}
function world(){const g=x.createLinearGradient(0,0,0,H*.62);g.addColorStop(0,'#0c2940');g.addColorStop(1,'#6fa37e');x.fillStyle=g;x.fillRect(0,0,W,H);x.fillStyle='#193f31';x.beginPath();x.moveTo(0,H*.34);for(let a=0;a<=W;a+=35)x.lineTo(a,H*.28-Math.sin(a*.08)*18);x.lineTo(W,H*.62);x.lineTo(0,H*.62);x.fill();const h=H*.28;x.fillStyle='#815f3e';x.beginPath();x.moveTo(W*.43,h);x.lineTo(W*.57,h);x.lineTo(W*.94,H);x.lineTo(W*.06,H);x.closePath();x.fill();for(let i=0;i<14;i++){const y=h+i/14*(H-h),t=(y-h)/(H-h);x.strokeStyle=`rgba(230,200,150,${.1+t*.08})`;x.lineWidth=1+t*3;x.beginPath();x.moveTo(W/2-W*(.07+.38*t),y);x.lineTo(W/2+W*(.07+.38*t),y);x.stroke()}for(const s of[-1,1])for(let i=0;i<7;i++)tree(W/2+s*(W*.13+i*W*.055),h+40+i*92,.35+i*.15)}
function tree(px,py,s){x.save();x.translate(px,py);x.scale(s,s);x.fillStyle='#5a3922';x.fillRect(-5,-36,10,44);x.fillStyle='#1d6b45';x.beginPath();x.arc(0,-42,25,0,7);x.arc(-15,-28,20,0,7);x.arc(15,-28,20,0,7);x.fill();x.restore()}
function proj(z,l){const h=H*.29;return{x:laneX(l,z),y:h+H*.49*Math.pow(Math.max(0,z),1.45),s:.25+z*.9}}
function enemy(e){if(e.dead)return;const q=proj(e.z,e.lane);x.save();x.translate(q.x,q.y);x.scale(q.s,q.s);if(e.hit)x.globalAlpha=.45;x.fillStyle='#0005';x.beginPath();x.ellipse(0,17,e.size*.75,8,0,0,7);x.fill();x.fillStyle=e.color;if(e.kind==='slime'){x.beginPath();x.arc(0,0,e.size*.7,Math.PI,0);x.lineTo(e.size*.7,15);x.lineTo(-e.size*.7,15);x.fill()}else{x.beginPath();x.arc(0,-6,e.size*.58,0,7);x.fill();x.fillRect(-e.size*.45,2,e.size*.9,e.size*.78)}x.fillStyle='#fff';x.fillRect(-10,-10,6,6);x.fillRect(4,-10,6,6);x.fillStyle='#111';x.fillRect(-8,-8,3,3);x.fillRect(6,-8,3,3);const bw=e.kind==='boss'?76:52;x.fillStyle='#000a';x.fillRect(-bw/2,-e.size-24,bw,7);x.fillStyle=e.kind==='boss'?'#ef476f':'#70e000';x.fillRect(-bw/2,-e.size-24,bw*Math.max(0,e.hp/e.maxHp),7);x.restore()}
function drawChest(q){if(q.opened)return;const a=proj(q.z,q.lane);x.save();x.translate(a.x,a.y);x.scale(a.s,a.s);x.fillStyle='#8b5a2b';x.fillRect(-23,-15,46,28);x.fillStyle='#d8a435';x.fillRect(-3,-15,6,28);x.fillRect(-23,-3,46,5);x.restore()}
function player(){const px=laneX(p.lane,1),py=p.y;x.save();x.translate(px,py);if(p.inv>0&&Math.floor(p.inv*20)%2===0)x.globalAlpha=.35;x.fillStyle='#0005';x.beginPath();x.ellipse(0,24,32,10,0,0,7);x.fill();const ac=['#405a70','#8b5e3c','#607d8b','#546e7a','#7a8899'];x.fillStyle=ac[Math.min(p.armor-1,4)];x.fillRect(-22,-33,44,48);x.fillStyle='#d7a679';x.beginPath();x.arc(0,-48,17,0,7);x.fill();x.fillStyle='#3b2a20';x.beginPath();x.arc(0,-54,18,Math.PI,0);x.fill();if(p.armor>1){x.fillStyle='#b0bec5';x.fillRect(-28,-30,10,22);x.fillRect(18,-30,10,22)}x.strokeStyle='#28323c';x.lineWidth=9;x.beginPath();x.moveTo(-10,14);x.lineTo(-13,35);x.moveTo(10,14);x.lineTo(13,35);x.stroke();x.save();x.translate(18,-18);x.rotate(p.swing>0?-1.25:-.35);const wc=['#b8c1cc','#d08c60','#7bd389','#dbe4ea','#ffd166'];x.strokeStyle=wc[Math.min(p.weapon-1,4)];x.lineWidth=6;x.beginPath();x.moveTo(0,0);x.lineTo(0,-48-p.weapon*2);x.stroke();x.fillStyle='#6b4423';x.fillRect(-5,-2,10,18);x.restore();x.restore()}
function draw(){x.clearRect(0,0,W,H);world();if(run){[...run.chests.map(o=>({...o,t:'c'})),...run.enemies.map(o=>({...o,t:'e'}))].sort((a,b)=>a.z-b.z).forEach(o=>o.t==='e'?enemy(o):drawChest(o))}player();for(const a of parts){x.globalAlpha=Math.max(0,a.life/.55);x.fillStyle=a.col;x.fillRect(a.x,a.y,5,5)}x.textAlign='center';x.font='800 18px system-ui';for(const f of floats){x.globalAlpha=Math.max(0,f.life/.8);x.fillStyle=f.col;x.fillText(f.t,f.x,f.y)}x.globalAlpha=1}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function bind(id,fn){$(id).addEventListener('pointerdown',e=>{e.preventDefault();fn()})}bind('play',newRun);bind('again',newRun);bind('left',()=>move(-1));bind('right',()=>move(1));bind('attack',attack);bind('dodge',dodge);bind('equip',equip);bind('sell',sell);addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='a')move(-1);if(e.key==='ArrowRight'||e.key==='d')move(1);if(e.key===' '||e.key==='j')attack();if(e.key==='Shift'||e.key==='k')dodge()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
